// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniCoreApi1.Models;

#nullable disable

namespace MiniCoreApi1.Migrations
{
    [DbContext(typeof(MiniCoreVentasContext))]
    [Migration("20240414183520_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MiniCoreApi1.Models.Vendedor", b =>
                {
                    b.Property<int>("IdVendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idVendedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVendedor"), 1L, 1);

                    b.Property<string>("NombreVendedor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdVendedor")
                        .HasName("vendedores");

                    b.ToTable("vendedores", (string)null);
                });

            modelBuilder.Entity("MiniCoreApi1.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idVenta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"), 1L, 1);

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("date")
                        .HasColumnName("fechaVenta");

                    b.Property<int>("IdVendedor")
                        .HasColumnType("int")
                        .HasColumnName("idVendedor");

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.Property<string>("Ventas")
                        .IsRequired()
                        .HasMaxLength(900)
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("ventas");

                    b.HasKey("IdVenta")
                        .HasName("PK__Venta__91431FE1C0001ED1");

                    b.HasIndex("IdVendedor");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("MiniCoreApi1.Models.Venta", b =>
                {
                    b.HasOne("MiniCoreApi1.Models.Vendedor", "IdVendedorNatvigation")
                        .WithMany("Ventas")
                        .HasForeignKey("IdVendedor")
                        .IsRequired()
                        .HasConstraintName("FK_PersonasOrder");

                    b.Navigation("IdVendedorNatvigation");
                });

            modelBuilder.Entity("MiniCoreApi1.Models.Vendedor", b =>
                {
                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
